version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ecomart
      POSTGRES_USER: ecomart_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=ecomart
      - DB_USER=ecomart_user
      - DB_PASSWORD=password
    depends_on:
      - db

volumes:
  postgres_data: